# Generated by Django 5.1.5 on 2025-01-27 10:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_privatemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=datetime.datetime(2025, 1, 27, 10, 14, 36, 961384, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
