# Generated by Django 5.1.5 on 2025-01-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_participants_message_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
